tpdc = load('TPDC.txt');
tpdu = load('TPDU.txt');
tpcb=load('TPCB.txt');
fpdc=load('FPDC.txt');
fpdu=load('FPDU.txt');
fpcb=load('FPCB.txt');

s=load('dcondit.txt');
ss = load('ducondit.txt');
scb=load('cbcondit.txt');
% dc on cbset   pos : dc,..   neg : du
% pos = tpdc,..  neg = tpdu       where tpdu is generated by running dc
% over du, this is accomplished by using due.fa for the ecolisites.
% P = fn + tp,...        P is simply 89 ( n),.. while negative N = fp + tn, which is simply 225 ( the du data,.. we need a new n here for the du data...) 
n=length(scb);

%the FPs are stored in FPs directory, where they were generated from NEE
%and Rep seqs.  This allowed the TPs to be masked out from the FP data by
%subtracting out the number of Trues from the number of total Falses..
%scatter( (fpdc(:,1)-tpdc(:,1) )./(fpdc(end,1)-tpdc(end,1)),tpdc(:,1)./tpdc(end,1),'r')
%x=0:1/s:1;
hold on 
%plot( fpdu(:,1),tpdu(:,1)./n,'g')
%plot(( fpcb(:,1) -tpcb(:,1) )./(fpcb(end,1) - tpcb(end,1)),tpcb(:,1)./tpcb(end,1),'k')
xmix=( fpdc(:,1) -tpdc(:,1) )./(fpdc(end,1) - tpdc(end,1));
ymix=tpdc(:,1)./tpdc(end,1);
xcb=( fpcb(:,1) -tpcb(:,1) )./(fpcb(end,1) - tpcb(end,1));
ycb=tpcb(:,1)./tpcb(end,1);
plot(( fpdc(:,1) -tpdc(:,1) )./(fpdc(end,1) - tpdc(end,1)),tpdc(:,1)./tpdc(end,1),'g',( fpcb(:,1) -tpcb(:,1) )./(fpcb(end,1) - tpcb(end,1)),tpcb(:,1)./tpcb(end,1),'r')
set(gca,'XLim' , [0 .06])
set(gca,'YLim' , [0 .75])
set(gca,'FontSize',15)
 ylabel('TPR','FontSize',15)
 xlabel('FPR','FontSize',15)
 lineobj = findobj('type', 'line');
 set(lineobj, 'linewidth', 3);
legend('OR','CB')
print(gcf,'-depsc','rocenha.eps')
