tpdc = load('TPDC.txt');
tpdu = load('TPDU.txt');
tpcb=load('TPCB.txt');
fpdc=load('FPDC.txt');
fpdu=load('FPDU.txt');
fpcb=load('FPCB.txt');

s=load('dcondit.txt');
ss = load('ducondit.txt');
scb=load('cbcondit.txt');
ncb =length(scb);
% dc on cbset   pos : dc,..   neg : du
% pos = tpdc,..  neg = tpdu       where tpdu is generated by running dc
% over du, this is accomplished by using due.fa for the ecolisites.
% P = fn + tp,...        P is simply 89 ( n),.. while negative N = fp + tn, which is simply 225 ( the du data,.. we need a new n here for the du data...) 
ndc=length(s);
ndu = max(fpdu);    %length(ss) + 1;

scatter( fpdc(:,1)./fpdc(end,1),tpdc(:,1)./tpdc(end,1),'r')
x=0:1/ndc:1;
hold on
set(gca,'FontSize',18)
ylabel('frequency of pvalue ','FontSize',18,'FontName','Times')

% hold on 
%title('ROC for DC and DU detectors using their training data')
scatter( fpdu(:,1)./fpdu(end,1),tpdu(:,1)./tpdu(end,1),'b')
%scatter( fpcb(:,1)./fpcb(end,1),tpcb(:,1)./tpcb(end,1),'k')
 
plot(x,x,'k','LineWidth',1.5)
legend('D_c','D_u','random',3,'FontSize',18,'FontName','Times');
ylabel('TP/(TP + FN) = TPR','FontSize',18,'FontName','Times')
xlabel('FP/(FP + TN) = FPR','FontSize',18,'FontName','Times')
print(gcf,'-depsc','rocp.eps')
%hold off
% plot( fpcb(:,1)./n,tpcb(:,1)./n,'k')
